[project]
name = "smart-mobility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networks>=0.3.7",
    "pandas>=2.2.3",
    "pyvis>=0.3.2",
    "streamlit>=1.45.1",
]
